### PR TITLE
Add conda-forge/event-model and mrakitin as maintainers

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@CJ-Wright, @conda-forge/core, can I please be added as a maintainer? We at NSLS-II / bluesky orgs own this project. Thanks!

**Comment by mrakitin** [comment]
@conda-forge/core, we need an updated version of this package for https://github.com/conda-forge/staged-recipes/pull/15764. Could you please add me as a maintainer asap? Thanks!

**Review by dopplershift — APPROVED** [review]
👍 since @mrakitin is on both upstream PyPI and GitHub repos.

**Comment by mrakitin** [comment]
Thanks, @dopplershift! Greatly appreciate your help with that request :)

**Pull request merged**
